# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('date', models.DateField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(max_length=255)),
                ('window_width', models.IntegerField(blank=True, null=True)),
                ('window_height', models.IntegerField(blank=True, null=True)),
                ('screen_width', models.IntegerField(blank=True, null=True)),
                ('screen_height', models.IntegerField(blank=True, null=True)),
                ('device_pixel_ratio', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Mobile',
                'verbose_name': 'Mobile',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('referer', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Stats',
                'verbose_name': 'Stats',
            },
        ),
    ]
